otc:
  obs:
    bucket-name: neuris-document-storage-staging

error:
  nodes:
    active: true

spring:
  data:
    redis:
      host: redis
      username: redis
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      config:
        fail-fast: true
        sources:
          - name: ris-search-config

sentry:
  environment: staging
  traces-sample-rate: 0.1
