name: Bump images

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 8am
  # Allow to run this workflow manually
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-chainguard-images:
    uses: ./.github/workflows/_bump-chainguard-digest.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - imageName: nginx
            filePath: frontend/Dockerfile.prod
          - imageName: redis
            filePath: compose.yaml
    with:
      imageName: ${{ matrix.imageName}}
      filePath: ${{ matrix.filePath }}
