name: Bump images

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 8am
  # Allow to run this workflow manually
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-chainguard-images:
    runs-on: ubuntu-latest
    steps:
      - name: bump nginx image
        uses: digitalservicebund/github-actions/bump-chainguard-digest@8a13fd118e53df5b241d3309b3a1d4e4c355bb20
        with:
          imageName: nginx
          filePath: frontend/Dockerfile.prod
      - name: bump redis image
        uses: digitalservicebund/github-actions/bump-chainguard-digest@8a13fd118e53df5b241d3309b3a1d4e4c355bb20
        with:
          imageName: redis
          filePath: compose.yaml

  trigger-pipeline:
    needs: bump-chainguard-images
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: gh workflow run pipeline.yml
        env:
          GH_TOKEN: ${{ github.token }}
